# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.hostname = 'centos65-x64-puppet'
  config.vm.box = "puphpet/centos65-x64"

  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.synced_folder "../shared/www", "/var/www/"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # Pre-provisionado de módulos
  config.vm.provision "shell", path: "scripts/install_modules.sh"

  # Provision de Puppet
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path   = "environments/development/manifests"
    puppet.manifest_file    = "site.pp"
    puppet.module_path      = "modules"
  end

end
